config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :impact_types
  resources :reporters
  resources :articles
  resources :impacts
  resources :users
  resources :projects
  resources :impact_records
  get '/search' => 'articles#search'
  get '/impact_search' => 'impacts#search'
  root "impact_types#index"
#should remove this duplicate
  get '/impact_search' => 'impacts#article_selector'
  get '/basic_search' =>'impacts#basic_search'
  get '/impact_add_search' => 'impacts#impact_add_search', as: 'impact_add_search'
  get "/sign_in" => "sessions#new", as: 'new_session'
  post "/sessions" => "sessions#create"
  get "/profile" => "users#profile", as: 'profile'
  get "/reporters/:id/search" => "reporters#search_results", as: 'reporter_search'
  get "/log_out" => "sessions#destroy"
  get "impact_selector" => "impacts#selector", as: 'impact_selector'
  get "impact_selector/:id" => "impacts#selector", as: 'impact_selector_id'
  #adding new articles
  get '/add_from_home/:article/:impact_id' => "impact_records#add_from_home", as: 'add_from_home'
  #adding new projects
  get '/add_from_home_project/:project/:impact_id' => "impact_records#add_from_home_project", as: 'add_from_home_project'
  get '/download/:id' => 'articles#articles_download', as: 'download'
  get '/project_download/:id' => 'projects#project_download', as: 'project_download'
  get '/download_impacts' => 'impacts#download', as: 'download_impacts'
  get '/stats' => 'impact_records#stats'
  get '/stats_select/:type' => 'impact_records#stats_select', as: 'stats_select'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/impact.rb
class Impact < ApplicationRecord
  has_many :article_impacts
  has_many :articles, through: :article_impacts
  has_many :impact_records
  has_many :impact_types, through: :impact_records
  belongs_to :user


  def self.search(term)
    Impact.where("name like ?", "%#{term}%")
  end

  def publication
    self.user.publication
  end

  def impact_type
    self.impact_records.first.impact_type
  end

  def self.impacts_from(publication)
    self.all.select{|impact|impact.user.publication==publication}
  end

  def self.current_publication
    #this method may fail because I created the publication method.
    Impact.all.where(publication: current_user.publication)
  end


end

app/models/impact_type.rb
class ImpactType < ApplicationRecord
  has_many :impact_records
  has_many :impacts, through: :impact_records

def addition_name
  addition_name_hash = {"Law change/Policy change"=>"law/policy change",
  "Legal Impact"=>"legal impact",
  "Government Investigation" => "government investigation",
  "Media Impact" => "media impact",
  "Social Media" => "social media impact",
  "Award"=>"award",
  "Community Engagement"=>"community engagement",
  "Referenced by Key Individual"=>"reference by a key individual",
  "Major Citation"=>"major citation",
  "Institutional Action"=>"institutional action",
  "Advocacy Impact"=>"advocacy impact",
  "Legislation Introduced" =>"legislation being introduced"}
  addition_name_hash[self.name]
end

end

app/controllers/impacts_controller.rb
class ImpactsController < ApplicationController
  # before_action :impact_add_search, only: [:index, :create, :update]

  def index
  end

  def selector

  end

  def download
    impacts = ""

    impacts << "Impacts: \n\n"

    params[:impacts].each do |impact_id|
      impact = Impact.find(impact_id)
      impacts << "Article: " + impact.impact_records.first.article.headline + "\n"
      impacts << "By: " + impact.impact_records.first.article.reporter_name + "\n"
      impacts << "Impact type: " + impact.impact_types.first.name + "\n"
      impacts << "Impact description: " + impact.description + "\n"
      impacts << "Impact date: " + impact.impact_date.to_s + "\n\n"
    end

    send_data impacts,
      :type => 'text',
      :disposition => "attachment; filename=" + "Impact_search_" + Time.now.to_s
  end

  def article_selector
    @reporters = Reporter.all
    @articles = Article.search(params[:search])
  end

  def impact_add_search
    # @article = Article.search(params[:search]).first
  end


  def search
    impact_types_array = params[:impact][:impact_types].map{|type_id|type_id.to_i}
    impacts_of_specified_types = ImpactRecord.collect_records_having_these_impact_types(impact_types_array).flatten
    #now to select out for relevant publication
    publication_impacts = impacts_of_specified_types.select do |impact|
      #have to include conditional b/c for now not all impacts have users. can remove for production.
      if impact.impact.user_id
        impact.impact.user.publication == current_user.publication
      end
    end
    relevant_impacts = publication_impacts.map{|impact_record| impact_record.impact}
    @relevant_dates = date_selector(relevant_impacts, params[:impact][:start], params[:impact][:end])
  end

  def basic_search
    byebug;
  end

  def date_selector(array, start_date, end_date)
    array.select do |impact|
      if impact.impact_date
        formatted_date = impact.impact_date.strftime("%Y-%m-%d")
        formatted_date > start_date && formatted_date < end_date
      end
    end
  end

end

app/views/impacts/_impacts_display.html.erb
<%impacts.each do |impact|%>
  <div class="impact_bubbles">
    <div class="impact_package large">

      <div class="impact_bubble article">
        <img class="icon" src=<%=impact.impact_types.first.image%>></img>
        <!-- <%=impact.impact_types.first.name%> -->
        <%if impact.impact_date%>
          <em>
            <h6 id="impact_bubble_date">
              <%=impact.impact_date.strftime("%m/%d/%Y")%>
            </h6>
          </em>
        <%end%>

        <div class="impact_bubble_text">
          <h4>
            <%=impact.impact_records.first.article.headline%>
          </h4>
          <h5>
            <%=impact.description%>
          </h5>
        </div>
      </div>
    </div>
  </div>
<%end%>
<a href=<%=download_impacts_path(:impacts => impacts)%>>
  <img class="icon small download_icon" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Download_media.svg/453px-Download_media.svg.png">
</a>

app/views/impacts/_impacts_display_impact_focused.html.erb
<%impacts.each do |impact|%>
  <div class="impact_bubbles">
    <div class="impact_package large fill">
      <div class="impact_bubble article">
        <img class="icon" src=<%=impact.impact_types.first.image%>></img>
        <%if impact.impact_date%>
          <em>
            <h6 id="impact_bubble_date">
              <%=impact.impact_date.strftime("%m/%d/%Y")%>
            </h6>
          </em>
        <%end%>
        <div class="impact_bubble_text left_padded">
          <h4><%=impact.description%></h4>
          <h5 style="font-style:italic">
            <%if impact.impact_records.first.article%>
              <a href="<%=article_path(impact.impact_records.first.article)%>"><%=impact.impact_records.first.article.headline%></a>
            <%elsif impact.impact_records.first.project%>
              <a href="<%=project_path(impact.impact_records.first.project)%>"><%=impact.impact_records.first.project.name%></a>
            <%end%>
          </h5>
        </div>
      </div>
    </div>
  </div>
<%end%>
<!-- <a class = "edit_button" href=<%=download_impacts_path(impacts)%>>Download <br>search results</a> -->

app/views/impacts/article_selector.html.erb
<div class="dropdown_and_search">
  <div class="col-lg-1">
    <div class="btn-group" id="reporter_dropdown">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Reporters <span class="caret"></span></button>
      <ul class="dropdown-menu scrollable-menu" role="menu">
        <%@reporters.each do |reporter|%>
          <li>
            <a href=<%=reporter_search_path(reporter.id)%>>
              <%=reporter.name%>
            </a>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
  <%= render partial: "./articles/article_search"%>
</div>
<br><br><br>

Select An Article

<%@articles.each do |article|%>
  <div class="col-sm-4">
    <%= render partial: "./articles/article_display", locals: { article: article } %>
  </div>
<%end%>

app/views/impacts/basic_search.js.erb
$('#basic_search_results').html("<%= j render(:partial => 'impacts_display', :locals => { impacts: @relevant_impacts }) %>");

app/views/impacts/impact_add_search.js.erb
$('#article_choices').html("<%= j render(:partial => './articles/articles_display_add', :locals => { articles: Article.search(params[:search])}) %>");

app/views/impacts/index.html.erb
<div class="btn-group" id="section_toggle" role="group">
      <button type="button" class="btn btn-default" id="toggle_impact"  style="background-color: #d3d3d3; box-shadow: 1px 1px 5px #555 inset;">
        Impacts
      </button>
    <a href="<%=articles_path%>">
      <button type="button" class="btn btn-default" id="toggle_article">
        Stories
      </button>
    </a>
</div>

<%= form_tag "/impact_search", method: "get" , remote: true, class: "navbar-form"  do %>
   <div class="centered_header">
     Select impact type(s)
   </div>
<div id="impact_checkboxes">
  <%=collection_check_boxes(:impact, :impact_types, ImpactType.all, :id, :name)do |b|%>
    <%= b.label class:"label-checkbox" do%>
        <%=b.check_box(class: "check_box", id: b.object.image)%>
          <label class="type_icon" for="<%=b.object.image%>" id="<%=b.object.id%>b"></label>
          <script>
              $('input[type="checkbox"] + label#<%=b.object.id%>b').css("background", "url(<%=b.object.image%>) no-repeat center").css("background-size", "cover");
              $('input[type="checkbox"] + label').on("click", function(){
                $(this).css("background", "url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Check_green_icon.svg/2000px-Check_green_icon.svg.png) no-repeat center").css("background-size", "cover");
              })
              $('input[type="checkbox"] + label#<%=b.object.id%>b').hover(function(){
                  $('#descriptor<%=b.object.id%>').empty();
                  $('#descriptor<%=b.object.id%>').html("<p><%=b.object.name%></p>");
                  $('input[type="checkbox"] + label').css("opacity", "1.0");
                  $(this).css("opacity", ".8");
                })
              $('input[type="checkbox"] + label#<%=b.object.id%>b').mouseout(function(){
                $('#descriptor<%=b.object.id%>').empty();
              })

              $('#select_all').on("click", function(){
                $('input[type="checkbox"]').prop('checked', true);
                var num_array = [1,2,3,4,5,6,7,8,9,10,11,12]
                num_array.forEach(function(num){
                  $('#'+String(num)+'b').css("background", "url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Check_green_icon.svg/2000px-Check_green_icon.svg.png) no-repeat center").css("background-size", "cover");
                })
              })
          </script>
      <%end%>
      <div class="descriptor" id='descriptor<%=b.object.id%>'></div>
  <%end%>

    <div id="select_all">
      <button class="btn btn-primary" style="float: right">
        Select All
      </button>
    </div>

  <div id="impact_date_selector">
    between
    <%= date_field(:impact, :start) %>
    and
    <%= date_field(:impact, :end) %>
    <%= submit_tag("Search", id: "impact_search_submit", class: "btn btn-success") %>
  </div>
<% end %>
<br><br>

  <div id="impact_search_results"></div>
  <script>
  $('#select_all').on("click", function(){
    $('input[type="checkbox"]').prop('checked', true);
    var num_array = [1,2,3,4,5,6,7,8,9,10,11,12]
    num_array.forEach(function(num){
      $('#'+String(num)+'b').css("background", "url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Check_green_icon.svg/2000px-Check_green_icon.svg.png) no-repeat center").css("background-size", "cover");
    })
  })
  </script>
</div>

app/views/impacts/search.js.erb
$('#impact_search_results').html("<%= j render(:partial => 'impacts_display', :locals => { impacts: @relevant_dates }) %>");

app/views/impacts/selector.html.erb
  <div id="selector_containers">
    <div class="selector_container">
        <h3>
          Which story or project led to the <%=ImpactType.find(params[:id]).addition_name%>? Please search below.
        </h3>
        <h6>
          <em>
            Note: if the impact is tied to a project as a whole, choose that project. If it's tied to a particular story, choose that story.
          </em>
        </h6>
        <%= form_tag "/impact_add_search", :method => 'get', remote: true, class: "navbar-form navbar-left" do %>
          <div class="form-group">
            <input id="selector_value" type="text" name="search" class="form-control">
            <input style="display:none" type="text" name="impact_id" value=<%=params[:id]%>>
          </div>
          <button type="submit" class="btn btn-success">Search</button>
        <%end%>
    </div>
    <div class="selector_container" id="second_selector">
        <h3>Don't see it listed in the search results?</h3><br>
        <button class="btn btn-default"><%= link_to 'Add a new story', new_article_path%></button>
        <button class="btn btn-default"><%= link_to 'Add a new project', new_project_path%></button>
    </div>
  </div>

<div id="article_choices"></div>