config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :impact_types
  resources :reporters
  resources :articles
  resources :impacts
  resources :users
  resources :projects
  resources :impact_records
  get '/search' => 'articles#search'
  get '/impact_search' => 'impacts#search'
  root "impact_types#index"
#should remove this duplicate
  get '/impact_search' => 'impacts#article_selector'
  get '/basic_search' =>'impacts#basic_search'
  get '/impact_add_search' => 'impacts#impact_add_search', as: 'impact_add_search'
  get "/sign_in" => "sessions#new", as: 'new_session'
  post "/sessions" => "sessions#create"
  get "/profile" => "users#profile", as: 'profile'
  get "/reporters/:id/search" => "reporters#search_results", as: 'reporter_search'
  get "/log_out" => "sessions#destroy"
  get "impact_selector" => "impacts#selector", as: 'impact_selector'
  get "impact_selector/:id" => "impacts#selector", as: 'impact_selector_id'
  #adding new articles
  get '/add_from_home/:article/:impact_id' => "impact_records#add_from_home", as: 'add_from_home'
  #adding new projects
  get '/add_from_home_project/:project/:impact_id' => "impact_records#add_from_home_project", as: 'add_from_home_project'
  get '/download/:id' => 'articles#articles_download', as: 'download'
  get '/project_download/:id' => 'projects#project_download', as: 'project_download'
  get '/download_impacts' => 'impacts#download', as: 'download_impacts'
  get '/stats' => 'impact_records#stats'
  get '/stats_select/:type' => 'impact_records#stats_select', as: 'stats_select'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :reporter_articles
  has_many :reporters, through: :reporter_articles
  has_many :article_impacts
  has_many :impact_records
  has_many :impact_types, through: :impact_records
  has_many :impacts, through: :impact_records
  belongs_to :project

  def reporter
    self.reporters.first
  end

  def reporter_name
    self.reporters.map{|reporter| reporter.name}.first
  end

  def reporter_names
    self.reporters.map{|reporter| reporter.name}
  end

  def reporter_id
    self.reporters.map{|reporter| reporter.id}.first
  end

  def self.search(term)
    article_results = Article.where("upper(headline) like ?", "%#{term.upcase}%") + Article.where("headline like ?", "%#{term.capitalize}%")
    project_results = Project.where("upper(name) like ?", "%#{term.upcase}%") + Project.where("name like ?", "%#{term.capitalize}%")
    article_results.uniq + project_results.uniq
  end

  def publication
    self.reporters.first.publication
  end

  def reporter_names
    self.reporters.map{|reporter| reporter.name}
  end

  def self.articles_from(publication)
    self.all.select{|article|article.reporter.publication==publication}
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :search, only: [:index, :create, :update]

  def index
    @articles = Article.articles_from(current_user.publication)
    # limit reporters for dropdown to those of relevant publication
    @reporters = Reporter.reporters_from(current_user.publication)
  end

  def show
    @article = Article.find(params[:id])
  end

  def articles_download
    impacts = ""
    @article = Article.find(params[:id])
    impacts << @article.headline + "\n"
    impacts << "By " + @article.reporter_name + "\n\n"
    impacts << "Impacts: \n"
    Article.find(params[:id]).impacts.each do |impact|
      impacts << impact.impact_types.first.name + ": " + impact.description + "\n\n"
    end

    send_data impacts,
      :type => 'text',
      :disposition => "attachment; filename=" + @article.headline
  end

  def new
    @article = Article.new
    @reporters = Reporter.reporters_from(current_user.publication)
    @projects = Project.all
  end

  def create
    if params[:reporter][:reporters].empty?
      flash[:notice] = "Please list a reporter."
      redirect_to new_article_path
    else

      article = Article.create({headline: params[:article][:headline],url: params[:article][:url],info: params[:article][:info],date: params[:article][:date], project_id: project_id_decider(params[:article][:project_id])})
      params[:reporter][:reporters].each do |reporter_name|
        article.reporters << Reporter.find_by(name: reporter_name)
      end
      redirect_to article_path(article.id)
    end
  end

  def project_id_decider(params)
    params.blank? ? 1.to_s : params
  end

  def search
    # @articles = Article.search(params[:search])
    # @reporters = Reporter.all
  end

  def edit
    @article = Article.find(params[:id])
    #only allow editors or article authors to edit articles
    if current_user.is_reporter && @article.reporter_names.include?(current_user.name) == false
      flash[:notice] = "Only an article's reporters can edit the article."
      redirect_to article_path(@article)
    end
      @reporters = Reporter.reporters_from(current_user.publication)
      @projects = Project.all
  end

  def update
    @article = Article.find(params[:id])
    @article.headline = params[:article][:headline]
    @article.url = params[:article][:url]
    @article.info = params[:article][:info]
    @article.reporters = []
    params[:reporter][:reporters].each do |reporter_name|
      @article.reporters << Reporter.find_by(name: reporter_name)
    end
    @article.date = params[:article][:date]
    if params[:article][:project_id] != ""
      @article.project = Project.find(params[:article][:project_id])
    end
    @article.save
    redirect_to article_path(@article)
  end


end

private

def article_params
    params.require(:article).permit(:headline, :url, :info, :date, :reporters, :project_id)
end

app/views/articles/_article_display.html.erb
<div id="article_display_container">
  <div class="panel panel-default">
      <div class="panel-body"><h3><a href=<%=article_path(article.id)%>><%=article.headline%></a></h3>
        <h4>
          <%article.reporters.uniq.each do |reporter|%>
            <a href=<%=reporter_path(reporter)%>><%=reporter.name%></a>
        <%end%>
        </h4>
        <div class="panel-footer">
          <div class="impact_count" id="impact_count<%=article.id%>" onclick='showImpactList(<%=article.id%>)'>
            <strong><%=article.impact_types.distinct.length%>
            <%=article.impact_types.distinct.length > 1 ? "Impacts" : "Impact"%></strong>
          </div>
          <div class="impact_list" id="impact_list<%=article.id%>">
            <%article.impact_types.distinct.each do |impact|%>
            <li><%=impact.name%><br></li>
            <%end%>
            <strong><a href=<%=new_impact_record_path(article.id)%>><em>Add Impact</em></a></strong> <button type="submit" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-plus"></span></button>
          </div>
      </div>
    </div>
</div>

app/views/articles/_article_search.html.erb
<%= form_tag "/search", :method => 'get', remote: true, class: "navbar-form navbar-right" do %>
  <div class="form-group">
    <input type="text" id="navbar_search" name="search" class="form-control" placeholder="Search articles and projects">
  </div>
  <button type="submit" class="btn btn-default">
    Submit
  </button>
<%end%>

app/views/articles/_articles_display.html.erb
<%articles.each do |article_or_project|%>
<%if article_or_project.class == Article %>
  <%if article_or_project.publication == current_user.publication %>
      <a href=<%=article_path(article_or_project.id)%>>
        <div class="col-sm-4">
          <div id="article_display_container">
          <div id="article_search_article" class="panel panel-default">
              <div class="panel-body">
                <h4><%=article_or_project.headline%></h4>
                <%article_or_project.reporters.pluck('name').uniq.each do |reporter_name|%>
                    <h5><%=reporter_name%></h5>
                <%end%>              <div id="impact_count">
                <%=article_or_project.impact_records.length%>
                <%=article_or_project.impact_records.length > 1 ? "Impacts" : "Impact"%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </a>
  <%end%>
<%elsif article_or_project.class == Project%>
  <a href=<%=project_path(article_or_project.id)%>>
  <div class="col-sm-4">
    <div id="article_display_container">
    <div id="article_search_article" class="panel panel-default">
        <div class="panel-body project">
          <h4><%=article_or_project.name%></h4>
        <div id="impact_count" style="color:white;">
          <%=article_or_project.impact_records.length%>
          <%=article_or_project.impact_records.length > 1 ? "Impacts" : "Impact"%>
        </div>
      </div>
    </div>
  </div>
  </div>
  </a>
<%end%>

<%end%>

app/views/articles/_articles_display_add.html.erb
<%articles.each do |article_or_project|%>
    <%if article_or_project.class == Article%>
      <%if article_or_project.reporters.map{|reporter|reporter.name}.include?(current_user.name) || current_user.title != "Reporter"%>
        <%if articles.length == 1%>
          <div class="col-sm-6">
        <%else%>
          <div class="col-sm-4">
        <%end%>
      <div id="article_display_container">
        <%imp_id = params[:impact_id]%>
        <a href="<%=add_from_home_path(article_or_project.id, imp_id)%>">
          <div class="panel panel-default">
              <div class="panel-body">
                <h4><%=article_or_project.headline%></h4>
                <%article_or_project.reporters.pluck('name').uniq.each do |reporter_name|%>
                    <h5><%=reporter_name%></h5>
                <%end%>
              </div>
            </div>
          </div>
        </a>
      </div>
      <%end%>
    <%elsif article_or_project.class == Project%>
        <%if articles.length == 1%>
          <div class="col-sm-6">
        <%else%>
          <div class="col-sm-4">
        <%end%>
       <div id="article_display_container">
        <%imp_id = params[:impact_id]%>
        <a href="<%=add_from_home_project_path(article_or_project.id, imp_id)%>">
          <div class="panel panel-default">
              <div class="panel-body project">
                <h4><%=article_or_project.name%></h4>
                <h5> project</h5>
            </div>
          </div>
        </a>
      </div>
    </div>
  <%end%>
<%end%>

app/views/articles/edit.html.erb
<div class="col-sm-8 form">
    <h1> Edit Article </h1>

    <%= bootstrap_form_for @article do |f| %>
      <%= f.text_field :headline, required: true %>
      <%= f.text_field :url, required: true %>
      <%= f.text_field :info %>
      <%= f.date_field :date, required: true %>
      <%= collection_select(:reporter, :reporters, @reporters.map{|reporter|reporter}, :name, :name, { include_hidden: false}, {:multiple => true, :class => "form-control"}) %>
      <%= f.select :project_id, options_for_select(@projects.map{|project|[project.name, project.id]}), :include_blank => true %>
      <%= f.submit %>
    <% end %>
</div>

app/views/articles/index.html.erb
<div class="btn-group" id="section_toggle" role="group">
  <a href="<%=impacts_path%>">
    <button type="button" class="btn btn-default" id="toggle_impact">
      Impacts
    </button>
  </a>
    <button type="button" class="btn btn-default" id="toggle_article" style="background-color: #d3d3d3; box-shadow: 1px 1px 5px #555 inset; position: absolute;">
      Stories
    </button>
</div>

<div class="dropdown_and_search">
  <div class="col-sm-1">
    <div class="btn-group" id="reporter_dropdown">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          Reporters
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu scrollable-menu" role="menu">
          <%@reporters.shuffle.each do |reporter|%>
            <li>
              <a href=<%=reporter_search_path(reporter.id)%> data-remote="true">
                <%=reporter.name%>
              </a>
            </li>
          <%end%>
        </ul>
    </div>
  </div>
  <%= render partial: "article_search"%>
</div>
<br><br><br>

<div id="article_search_results">
  <%@articles.shuffle[0..20].each do |article|%>
  <a href=<%=article_path(article.id)%>>
  <div class="col-sm-4">
    <div id="article_display_container">
      <div id="article_search_article" class="panel panel-default">
          <div class="panel-body">
            <h4><%=article.headline%></h4>
            <%article.reporters.pluck('name').uniq.each do |reporter_name|%>
                <h5><%=reporter_name%></h5>
            <%end%>
            <div id="impact_count">
              <%=article.impact_records.length%>
              <%=article.impact_records.length > 1 ? "Impacts" : "Impact"%>
            </div>
        </div>
      </div>
    </div>
  </div>
  </a>
  <%end%>
</div>

app/views/articles/new.html.erb
<% if flash[:notice]%>
  <div class="alert alert-warning"><%= flash[:notice] %></div>
<%end%>

<div class="col-sm-8 form">
  <h1> Add an Article </h1>

  <%= bootstrap_form_for @article do |f| %>
    <%= f.text_field :headline, required: true %>
    <%= f.text_field :url, label: 'URL', required: true %>
    <%= f.date_field :date, required: true, label: 'Online publication date' %>
    <%=f.label :reporters %>
    <%= collection_select(:reporter, :reporters, @reporters.map{|reporter|reporter}, :name, :name, { include_hidden: false}, {:multiple => true, :class => "form-control"}) %>
    <%= f.select :project_id, options_for_select(@projects.map{|project|[project.name, project.id]}), :include_blank => true%>
    <%= f.submit %>
  <% end %>
</div>

app/views/articles/search.html.erb
<%= render partial: "./reporters/reporter_dropdown", locals: { reporters: @reporters } %>
<%= render partial: "article_search"%>
<br><br><br>

<%= render partial: "articles_display", locals: { articles: @articles } %>

app/views/articles/search.js.erb
$('#article_search_results').html("<%= j render(:partial => 'articles_display', :locals => { articles: Article.search(params[:search]) }) %>");

app/views/articles/show.html.erb
<% if flash[:notice] %>
  <% if flash[:notice] == "Impact added!"%>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <%else%>
    <div class="alert alert-warning"><%= flash[:notice] %></div>
    <%end%>
<% end %>

<%if @article.reporter_name == current_user.name && @article.reporters.first.publication == current_user.publication || current_user.position.name != "Reporter"%>
  <div class="edit_button"><a href="<%=edit_article_path%>">Edit this article</a></div>
  <br>
<%end%>

<div id="article_header">
  <h1 id="article_headline_view"><a href=<%=@article.url%>><%=@article.headline%></a></h1>
  <div id="sub_head">
    <%if @article.reporters.length > 1%>
    <em>By
      <%@article.reporters.each do |reporter|%>
      <a href=<%=reporter_path(reporter)%>><%=reporter.name%></a>
      <%end%>
      | <%=@article.date.strftime("%B %d, %Y")%>
    </em>
    <%else%>
    <em>By
      <a href=<%=reporter_path(@article.reporter_id)%>><%=@article.reporter_name%></a>
      | <%=@article.date.strftime("%B %d, %Y")%>
    </em>
    <%end%>
  </div>
</div>


<%@article.impacts.distinct.each do |impact|%>
  <div class="impact_bubbles">
        <div class="impact_package large">
            <div class="impact_bubble article">
                <a href="<%=impacts_path%>">
                  <img class="icon" src=<%=impact.impact_types.first.image%>></img>
                </a>
                <%if impact.impact_date%>
                    <em><h6 id="impact_bubble_date"><%=impact.impact_date.strftime("%m/%d/%Y")%></h6></em>
                <%end%>
                <div class="impact_bubble_text">
                  <h4><%=impact.description.gsub(/\n/, '<br>').html_safe%></h4>
                </div>
                <%if impact.user && impact.impact_records.length > 0 && current_user == impact.user%>
                  <div class="edit_button">
                    <a href="<%=edit_impact_record_path(impact.impact_records.first.id)%>">
                      Edit
                    </a>
                  </div>
                <%end%>
            </div>
        </div>
  </div>
<%end%>

  <a href=<%=download_path(@article.id)%>>
    <img class="icon small download_icon" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Download_media.svg/453px-Download_media.svg.png">
  </a>

  <%if current_user.title != "Reporter" || @article.reporter_name == current_user.name && @article.reporters.first.publication == current_user.publication%>
    <h5 class="subhead"><strong><a href=<%=new_impact_record_path(@article.id)%>><em>Add Impact</em></a></strong></h5>
  <%end%>