config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :impact_types
  resources :reporters
  resources :articles
  resources :impacts
  resources :users
  resources :projects
  resources :impact_records
  get '/search' => 'articles#search'
  get '/impact_search' => 'impacts#search'
  root "impact_types#index"
#should remove this duplicate
  get '/impact_search' => 'impacts#article_selector'
  get '/basic_search' =>'impacts#basic_search'
  get '/impact_add_search' => 'impacts#impact_add_search', as: 'impact_add_search'
  get "/sign_in" => "sessions#new", as: 'new_session'
  post "/sessions" => "sessions#create"
  get "/profile" => "users#profile", as: 'profile'
  get "/reporters/:id/search" => "reporters#search_results", as: 'reporter_search'
  get "/log_out" => "sessions#destroy"
  get "impact_selector" => "impacts#selector", as: 'impact_selector'
  get "impact_selector/:id" => "impacts#selector", as: 'impact_selector_id'
  #adding new articles
  get '/add_from_home/:article/:impact_id' => "impact_records#add_from_home", as: 'add_from_home'
  #adding new projects
  get '/add_from_home_project/:project/:impact_id' => "impact_records#add_from_home_project", as: 'add_from_home_project'
  get '/download/:id' => 'articles#articles_download', as: 'download'
  get '/project_download/:id' => 'projects#project_download', as: 'project_download'
  get '/download_impacts' => 'impacts#download', as: 'download_impacts'
  get '/stats' => 'impact_records#stats'
  get '/stats_select/:type' => 'impact_records#stats_select', as: 'stats_select'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :articles
  has_many :impact_records
  has_many :impact_types, through: :impact_records
  has_many :impacts, through: :impact_records
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    project = Project.create({name: params[:project][:name], description: params[:project][:description]})
    redirect_to project_path(project)
  end

  def show
    @project = Project.find(params[:id])
  end

  def project_download
    impacts = ""
    @project = Project.find(params[:id])
    impacts << @project.name + "\n\n"
    impacts << @project.description + "\n\n"
    impacts << "Articles: \n"
    Project.find(params[:id]).articles.each do |article|
      impacts << article.headline + " by " + article.reporter_name + "\n\n"
    end
    impacts << "\nImpacts: \n"
    Project.find(params[:id]).impacts.each do |impact|
      impacts << impact.impact_types.first.name + ": " + impact.description + "\n\n"
    end

    send_data impacts,
      :type => 'text',
      :disposition => "attachment; filename=" + @project.name
  end


end

app/views/projects/new.html.erb
<div class="col-sm-8 form">
  <h1> Add a Project </h1>

  <%= bootstrap_form_for @project do |f| %>
    <%= f.text_field :name, required: true, label: 'Name' %>
    <%= f.text_field :url, required: false, label: 'URL' %>
    <%= f.text_field :description, required: true, label: 'Description' %>
    <%= f.submit %>
  <% end %>
</div>

app/views/projects/show.html.erb
<% if flash[:notice] %>
  <% if flash[:notice] == "Impact added!"%>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <%else%>
    <div class="alert alert-warning"><%= flash[:notice] %></div>
    <%end%>
<% end %>


<div id="article_header">
  <%if @project.url == nil%>
    <h1 id="article_headline_view"><%=@project.name%></h1>
  <%else%>
    <a href="<%=@project.url%>"><h1 id="article_headline_view"><%=@project.name%></h1></a>
  <%end%>
  <h3><%=@project.description%></h3>
  <div id="sub_head">
  </div>

  <%if @project.articles.length > 0  %>
       <%= render partial: "./articles/articles_display", locals: { articles: @project.articles} %>
   <%end%>


  <%@project.impacts.distinct.each do |impact|%>
      <div class="impact_bubbles">
      <div class="impact_package large">
        <!-- <img class="icon" src=<%=impact.impact_types.first.image%>></img> -->

        <div class="impact_bubble article">
          <a href="<%=impacts_path%>">
            <img class="icon" src=<%=impact.impact_types.first.image%>></img>
          </a>
          <!-- <%=impact.impact_types.first.name%> -->
          <%if impact.impact_date%>
            <em><h6 id="impact_bubble_date"><%=impact.impact_date.strftime("%m/%d/%Y")%></h6></em>
          <%end%>

            <div class="impact_bubble_text" style="text-align: left">
              <h4><%=impact.description.gsub(/\n/, '<br>').html_safe%></h4>
            </div>
            <%if impact.user && impact.impact_records.length > 0 && current_user == impact.user%>
              <div class="edit_button">
                <a href="<%=edit_impact_record_path(impact.impact_records.first.id)%>">
                  Edit
                </a>
              </div>
            <%end%>
        </div>
      </div>
    </div>

  <%end%>

  <a href=<%=project_download_path(@project.id)%>>
    <img class="icon small download_icon" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Download_media.svg/453px-Download_media.svg.png">
  </a>