config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :impact_types
  resources :reporters
  resources :articles
  resources :impacts
  resources :users
  resources :projects
  resources :impact_records
  get '/search' => 'articles#search'
  get '/impact_search' => 'impacts#search'
  root "impact_types#index"
#should remove this duplicate
  get '/impact_search' => 'impacts#article_selector'
  get '/basic_search' =>'impacts#basic_search'
  get '/impact_add_search' => 'impacts#impact_add_search', as: 'impact_add_search'
  get "/sign_in" => "sessions#new", as: 'new_session'
  post "/sessions" => "sessions#create"
  get "/profile" => "users#profile", as: 'profile'
  get "/reporters/:id/search" => "reporters#search_results", as: 'reporter_search'
  get "/log_out" => "sessions#destroy"
  get "impact_selector" => "impacts#selector", as: 'impact_selector'
  get "impact_selector/:id" => "impacts#selector", as: 'impact_selector_id'
  #adding new articles
  get '/add_from_home/:article/:impact_id' => "impact_records#add_from_home", as: 'add_from_home'
  #adding new projects
  get '/add_from_home_project/:project/:impact_id' => "impact_records#add_from_home_project", as: 'add_from_home_project'
  get '/download/:id' => 'articles#articles_download', as: 'download'
  get '/project_download/:id' => 'projects#project_download', as: 'project_download'
  get '/download_impacts' => 'impacts#download', as: 'download_impacts'
  get '/stats' => 'impact_records#stats'
  get '/stats_select/:type' => 'impact_records#stats_select', as: 'stats_select'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImpactTracker</title>
    <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <div class="container">
  <%if current_user%>
  <img id="pub_logo" src="http://www.gannett-cdn.com/sites/<%=current_user.publication.gannett_name%>/images/favicon.png"/>
  <%end%> -->

    <%if current_user%>
  <div id="navbar-desktop">

        <div class="navbar-header">

       <a class="navbar-brand" style="color: #d4eaf1" href="<%= root_url %>">Add Impact</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
      <% if current_user %>
      <li id="explore" ><%= link_to 'Explore', articles_path%></li>

         </ul>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><div style="font-size:20px; color: #f9ffff; margin-top: -13%">+</div></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New Article', new_article_path%></li>
            <li><%= link_to 'New Impact', impact_types_path%></li>
            <li><%= link_to 'New Project', new_project_path%></li>
          </ul>
        </li>
          <li class="dropdown">
            <a href="<%= profile_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: #d4eaf1;"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My Profile', profile_path%></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log Out', '/log_out'%></li>
            </ul>
          </li>
        </ul>
        <% else %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign In", new_session_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        </ul>
        <%end%>


      </ul>

      </div>
</div>
<div id="navbar_mobile">
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- <div class="navbar-header"> -->

      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
    <!-- </div> -->
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
  <% if current_user %>

  <ul class="nav navbar-nav">
    <li id="explore"><%= link_to 'Explore', articles_path%></li>
      <!-- <li><%= link_to 'Articles', articles_path%></li>
      <li><%= link_to 'Impacts', impact_type_path((1..ImpactType.all.length).to_a.sample)%></li> -->
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><div style="font-size:20px; color:#ce3936; margin-top: -13%">...</div></a>
        <ul class="dropdown-menu"  aria-labelledby="dropdownMenuButton">
          <li><%= link_to 'New Article', new_article_path%></li>
          <li><%= link_to 'New Impact', impact_types_path%></li>
          <li><%= link_to 'New Project', new_project_path%></li>
          <li><%= link_to 'My Profile', profile_path%></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'Log Out', '/log_out'%></li>
        </ul>
      </li>
  </ul>
    <% else %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign In", new_session_path %></li>
      <li><%= link_to "Sign Up", new_user_path %></li>
    </ul>
    <%end%>


  </ul>

  <!-- </div> -->
<!-- </div> -->
<!-- /.container-fluid -->
</nav>
</div>
<%end%>



    <%= yield %>
    </div>

  </div>

  </body>
</html>